config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts, only: [:show, :index]

  post 'photo' => 'photos#upload'

  namespace :admin do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, except: [:destroy]
    resources :sessions, only: [:new, :create, :destroy]
    root to: 'home#index', as: :root

    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end

    resources :accounts
    resources :users
    resources :words, concerns: :paginatable
  end

  get 'about' => 'home#about', as: :about
  get 'book' => 'home#book'

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id          :integer          not null, primary key
#  description :string           not null
#  price       :decimal(6, 2)    not null
#  created_at  :datetime         not null
#

class Account < ApplicationRecord
end

app/controllers/admin/accounts_controller.rb
module Admin
  # everyday payment
  class AccountsController < AdminController

    def index
      @account = Account.new
      @accounts = Account.order('ID DESC').page(params[:page]).per(10)
    end

    def create
      @account = Account.new(params_account)
      if @account.save
        redirect_to admin_accounts_path
      else
        render 'something wrong'
      end
    end

    def edit
      @account = Account.find(params[:id])
    end

    def update
      @account = Account.find(params[:id])
      if @account.update!(params_account)
        redirect_to admin_accounts_path
      else
        render 'somethig wrong'
      end
    end

    private

    def params_account
      params.require(:account).permit(:description, :price, :created_at)
    end
  end
end

app/views/admin/accounts/_new.html.erb
<div style="margin: 10px 0;">
  <%= form_for @account, url: admin_accounts_path do |f| %>
    <%= f.text_field :description, placeholder: "事项" %>
    <%= f.text_field :price, placeholder: "金额" %>
    <%= f.datetime_select :created_at %>
    <%= f.submit "新增开支" %>
  <% end %>
</div>

app/views/admin/accounts/edit.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      h3.text-center 修改账单

      = form_for @account, url: admin_account_path, method: :put do |f|
        .form-group
          = f.text_field :description, class: "form-control"
        .form-group
          = f.text_field :price, class: "form-control"
        .form-group
          = f.datetime_select :created_at, class: "form-control"
        .form-group
          = f.submit "提交修改", class: "form-control"

app/views/admin/accounts/index.html.erb
<% content_for :title do %>
  记账簿
<% end %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: 'new' %>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>事项</th>
          <th>金额</th>
          <th>时间</th>
          <th>管理</th>
        </tr>
      </thead>
      <tbody>
        <% @accounts.each do |account| %>
          <tr>
            <td><%= account.id %></td>
            <td><%= account.description %></td>
            <td><%= account.price %> 元</td>
            <td><%= account.created_at.strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= link_to "修改", edit_admin_account_path(account) %></td>
          </tr>
        <% end %>
      </tbody>
   </table>
   <div class="text-center"><%= paginate @accounts %></div>
  </div>
</div>
<div class="row">
  <%= column_chart Account.group_by_month(:created_at, format: "%b %Y").sum(:price) %>
</div>