config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts, only: [:show, :index]

  post 'photo' => 'photos#upload'

  namespace :admin do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, except: [:destroy]
    resources :sessions, only: [:new, :create, :destroy]
    root to: 'home#index', as: :root

    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end

    resources :accounts
    resources :users
    resources :words, concerns: :paginatable
  end

  get 'about' => 'home#about', as: :about
  get 'book' => 'home#book'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :integer          not null, primary key
#  title         :string(30)       default("我的日志"), not null
#  content       :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  url_title     :string
#  visited_count :integer          default(0), not null
#
# Indexes
#
#  index_posts_on_url_title  (url_title)
#

class Post < ApplicationRecord
  require 'chinese_pinyin'

  validates :title, presence: true, uniqueness: true, case_sensitive: false
  validates :url_title, presence: true, uniqueness: true
  validates :content, presence: true
  has_many :taggings
  has_many :tags, through: :taggings

  def to_param
    url_title
  end

  def self.tagged_with(name)
    Tag.find_by_name(name).try(:posts)
  end

  def all_tags=(names)
    names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(', ')
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < AdminController

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to admin_posts_path, notice: I18n.t('post.flash.create_success')
      else
        flash.now[:alert] = I18n.t('post.flash.blank_title_or_content')
        render :new
      end
    end

    def edit
      @post = Post.find_by_url_title!(params[:id])
    end

    def update
      @post ||= Post.find_by_url_title!(params[:id])
      if @post.update(post_params)
        redirect_to admin_posts_path, notice: t('post.flash.update_success')
      else
        flash.now[:alert] = t('post.flash.blank_title_or_content')
        render :edit
      end
    end

    def index
      tag = params[:tag]
      page = params[:page]
      if tag
        @posts_count = Tagging.post_count(tag)
        @posts = Post.tagged_with(tag).page(page).per(5)
      else
        @posts = Post.order(id: :desc).page(page).per(5)
      end
    end

    def show
      @post = Post.find_by_url_title!(params[:id])
      post_created_at = @post.created_at
      @prev = Post.where('created_at > ?', post_created_at).first
      @next = Post.where('created_at < ?', post_created_at).last
    end

    private

    def post_params
      params.require(:post).permit(:title, :url_title, :content, :all_tags)
    end
  end
end

app/controllers/posts_controller.rb
# posts controller
class PostsController < ApplicationController
  def index
    tag = params[:tag]
    page = params[:page]
    if tag
      @posts_count = Tagging.post_count(tag)
      @posts = Post.tagged_with(tag).page(page).per(5)
    else
      @posts = Post.order(id: :desc).page(page).per(5)
    end
  end

  def show
    @post = Post.find_by_url_title!(params[:id])
    @post.increment!(:visited_count)
    post_created_at = @post.created_at
    @prev = Post.where('created_at > ?', post_created_at).first
    @next = Post.where('created_at < ?', post_created_at).last
  end
end

app/helpers/post_helper.rb
module PostHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#{$1}" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end

  # 👹👹👹
  def numbers_of_content(post)
    content = strip_tags(post.content)
    content = content.for_each_continous_cjk_alpha_part
    content.inject(0) do |sum, word|
      if word.contains_cjk?
        sum += word.only_word.size
      else
        sum += word.gsub(/[\p{Punctuation}\p{Symbol}]|\u00A0/, '').split.size
      end
    end
  end

  def tag_links(tags)
    if current_admin?
      tags.split(',').map do |tag|
        link_to tag.strip, admin_tag_path(tag.strip)
      end.join(' ')
    else
      tags.split(',').map do |tag|
        link_to tag.strip, tag_path(tag.strip)
      end.join(' ')
    end
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, claaes[index.round])
    end
  end
end

app/views/admin/posts/_form.html.slim
.form-group
  = f.text_field :title, placeholder: t('post.title'), class: 'form-control'
.form-group
  = f.text_field :url_title, placeholder: t('post.url_title'), class: 'form-control'
.form-group
  = f.text_area :content, placeholder: t('post.content'), autofocus: true, rows: 20, id: 'editor', class: 'form-control'
.form-group
  = f.text_field :all_tags, placeholder: t('post.all_tags'), class: 'form-control'
.form-group
  = f.submit t('post.submit'), class: 'btn btn-default'

javascript:
  Admin.editor();

app/views/admin/posts/edit.html.slim
=title t('post.edit_form')
.container-fluid
  #post_edit_form
    .panel
      .panel-body
        = form_for @post, url: admin_post_path, method: :patch do |f|
          = render 'form', f: f

app/views/admin/posts/index.html.slim
.container-fluid
  #post_index
    .panel-body
      p.text-center= link_to '+', new_admin_post_path, class: "btn btn-success"
      ul
        - @posts.each do |post|
          li
            time.post_time_words= format_date post.created_at
            span.post_index_title=link_to emojify(post.title), admin_post_path(post)
    .post-footer
      .text-center
        = paginate @posts

app/views/admin/posts/new.html.slim
=title t('post.new_form')
.container-fluid
  #post_new_form
    .panel
      .panel-body
        = form_for @post, url: admin_posts_path do |f|
          = render 'form', f: f

app/views/admin/posts/show.html.slim
.container
  #post_show
    .post_show_title= emojify @post.title
    p.post_time_words
      span.updated_at= format_time @post.updated_at
      span
        = numbers_of_content @post
        | &nbsp;字
      span
        = @post.visited_count
        | &nbsp;次浏览
    .post-content= emojify raw(@post.content)
    .post_all_tags
      = raw tag_links(@post.all_tags)
    .post-footer.text-center
      =link_to t('post.edit_form'), edit_admin_post_path(@post),\
        class: 'btn btn-warning'
    .post_prev_next
      .pull-left= link_to '上一篇', admin_post_path(@prev) if @prev.present?
      .pull-right= link_to '下一篇', admin_post_path(@next) if @next.present?