config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts, only: [:show, :index]

  post 'photo' => 'photos#upload'

  namespace :admin do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, except: [:destroy]
    resources :sessions, only: [:new, :create, :destroy]
    root to: 'home#index', as: :root

    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end

    resources :accounts
    resources :users
    resources :words, concerns: :paginatable
  end

  get 'about' => 'home#about', as: :about
  get 'book' => 'home#book'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  pinyin     :string
#  birthday   :datetime
#  gender     :boolean
#  icon       :string
#  mobile     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'chinese_pinyin'

class User < ApplicationRecord
  before_save { self.pinyin = Pinyin.t(name, splitter: '') }

  def sex
    gender ? 'male' : 'female'
  end

  def zh_sex
    gender ? '他' : '她'
  end

  def age
    birthday.year - created_at.year
  end
end

app/controllers/admin/users_controller.rb
# encoding: utf-8

require 'chinese_lunar/lunar'

module Admin
  # admin manages users
  class UsersController < AdminController
    before_action :set_user, only: [:edit, :update]

    def index
      @china_day = ChineseLunar::Lunar.new.lunar_date
      @user = User.new
      @users = User.order(:birthday).page(params[:page]).per(20)
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path, flash: { success: 'user created successful' }
      else
        render :index
      end
    end

    def edit
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path, flash: { success: 'user update success' }
      else
        render :edit
      end
    end

    private

    def user_params
      params.require(:user).permit(:name, :pinyin, :created_at, :birthday, :gender, :icon, :mobile)
    end

    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/views/admin/users/_new.html.erb
<%= form_for @user, url: admin_users_path do |f| %>
  <%= f.text_field :name, placeholder: "姓名" %>
  <%= f.text_field :pinyin, placeholder: "拼音" %>
  <%= f.text_field :birthday %>
  <div class="form-group">
    <%= f.label :Gender %> <br />
    <%= f.label :Gender_male, 'male' %>
    <%= f.radio_button :gender, 'male', :checked => true %>
    <%= f.label :Gender_female, 'female' %>
    <%= f.radio_button :gender, 'female' %><br />
  </div>
  <%= f.text_field :mobile, placeholder: "手机" %>
  <%= f.submit "提交" %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 admin_user_form">
    <%= form_for @user, url: admin_user_path, method: :patch do |f| %>
      <div class="form-group">
        <label>姓名：</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>生日(农历)：</label>
        <%= f.date_field :created_at, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>过生(农历)：</label>
        <%= f.date_field :birthday, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>性别：</label>
        <%= f.label :Gender_female, '女' %>
        <%= f.radio_button :gender, false %>
        <%= f.label :Gender_male, '男' %>
        <%= f.radio_button :gender, true %>
      </div>
      <div class="form-group">
        <label>电话号码：</label>
        <%= f.phone_field :mobile, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "修改", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="row admin_user_index">
  <div class="col-md-4">
    <%= render partial: 'new' %>
  </div>
  <div class="col-md-6">
    <strong>今天是农历：<%= @china_day %></strong>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th></th>
          <th>姓名</th>
          <th>性别</th>
          <th>出日</th>
          <th>过生</th>
          <th>电话</th>
          <th>管理</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag letter_avatar_url(user.pinyin, 30) %></td>
            <td><%= user.name %></td>
            <td><%= I18n.t "users.gender.#{user.sex}" %></td>
            <td><%= user.created_at.to_date %></td>
            <td><%= user.birthday.to_date unless user.birthday.nil? %></td>
            <td><%= user.mobile %></td>
            <td><%= link_to "修改", edit_admin_user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
   </table>
   <div class="text-center"><%= paginate @users %></div>
  </div>
</div>