config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts, only: [:show, :index]

  post 'photo' => 'photos#upload'

  namespace :admin do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'

    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, except: [:destroy]
    resources :sessions, only: [:new, :create, :destroy]
    root to: 'home#index', as: :root

    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end

    resources :accounts
    resources :users
    resources :words, concerns: :paginatable
  end

  get 'about' => 'home#about', as: :about
  get 'book' => 'home#book'

end

app/views/layouts/_footer.html.slim
footer
  #footer
    .text-center
      p © Copyright 2017 by bscd

app/views/layouts/_header.html.slim
header
  #header
    .logo= link_to 'GLZ', root_path
    nav.nav.navbar-fixed-top
      .col= link_to 'Posts', posts_path
      .col.text-right= link_to "About", about_path

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>bscd - 控制台</title>
  <meta name="title" content="Admin Page Of <%= Yetting.app_name %>" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="爱好中医的rubist" />
  <meta name="author" content="高老庄">
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-toggleable-md fixed-top navbar-light bg-faded" style="height:3.4em;">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to("控制台", admin_root_path, class: "navbar-brand") %>
      </div>
      <nav class="collapse navbar-collapse" id="navbarSupportedContent">
        <%= render_list class: "nav navbar-nav mr-auto" do |li|
          li << link_to("高老庄", admin_root_path, class: "nav-link")
          li << link_to("日志", admin_posts_path, class: "nav-link")
          li << link_to("口水话", admin_words_path, class: "nav-link")
          li << link_to("家人", admin_users_path, class: "nav-link")
          li << link_to("支出", admin_accounts_path, class: "nav-link")
        end %>

        <%= render "shared/usernav" %>
      </nav>
    </div>
  </nav>
  <div id="contents">
    <%= render partial: 'header' %>
    <div class="container"><%= notice_message %></div>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || GLZ %></title>
  <meta name="title" content="glz Chinese blog" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="爱好中医的rubist" />
  <meta name="author" content="高老庄">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container"><%= notice_message %></div>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>